# Generated by Django 5.2.17 on 2026-10-05 18:55

import dineva.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('OWNER', 'Owner'), ('KITCHEN_STAFF', 'Kitchen Staff'), ('WAITER', 'Waiter')], max_length=20)),
                ('restaurant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_superuser', True), ('restaurant_id__isnull', True), ('role', 'SUPERADMIN')), models.Q(('is_superuser', False), ('restaurant_id__isnull', False), ('role__in', ['OWNER', 'KITCHEN_STAFF', 'WAITER'])), _connector='OR'), name='dineva_user_role_scope_valid')],
            },
            managers=[
                ('objects', dineva.models.UserManager()),
            ],
        ),
    ]
