# Generated by Django 5.2.17 on 2026-10-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dineva', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
