# Generated by Django 5.2.17 on 2026-10-06 11:59

from django.db import migrations, models


ROLE_PREFIXES = {
    "OWNER": "OWN",
    "WAITER": "WTR",
    "KITCHEN_STAFF": "KST",
}


def seed_sequences_and_public_ids(apps, schema_editor):
    User = apps.get_model("dineva", "User")
    Sequence = apps.get_model("dineva", "UserPublicIdSequence")
    using = schema_editor.connection.alias

    for role, prefix in ROLE_PREFIXES.items():
        next_value = 1
        for user in (
            User.objects.using(using)
            .filter(role=role, public_id__isnull=True)
            .order_by("created_at", "pk")
        ):
            user.public_id = f"{prefix}-{next_value:05d}"
            user.save(using=using, update_fields=["public_id"])
            next_value += 1

        Sequence.objects.using(using).update_or_create(
            role=role,
            defaults={"next_value": next_value},
        )


def clear_sequences_and_public_ids(apps, schema_editor):
    User = apps.get_model("dineva", "User")
    Sequence = apps.get_model("dineva", "UserPublicIdSequence")
    using = schema_editor.connection.alias
    User.objects.using(using).update(public_id=None)
    Sequence.objects.using(using).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dineva', '0003_customer_restaurant_remove_user_restaurant_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPublicIdSequence',
            fields=[
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('WAITER', 'Waiter'), ('KITCHEN_STAFF', 'Kitchen Staff')], max_length=20, primary_key=True, serialize=False)),
                ('next_value', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'db_table': 'user_public_id_sequences',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='public_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(
            seed_sequences_and_public_ids,
            clear_sequences_and_public_ids,
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('public_id__isnull', True), ('role', 'SUPERADMIN')), models.Q(('public_id__startswith', 'OWN-'), ('role', 'OWNER')), models.Q(('public_id__startswith', 'WTR-'), ('role', 'WAITER')), models.Q(('public_id__startswith', 'KST-'), ('role', 'KITCHEN_STAFF')), _connector='OR'), name='users_public_id_matches_role'),
        ),
    ]
