# Generated by Django 5.2.17 on 2026-10-06 19:02

import dineva.storage
import dineva.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_user_profiles(apps, schema_editor):
    User = apps.get_model("dineva", "User")
    UserProfile = apps.get_model("dineva", "UserProfile")
    using = schema_editor.connection.alias

    unexpected = User.objects.using(using).exclude(role="SUPERADMIN")
    if unexpected.exists():
        raise RuntimeError(
            "Employee migration aborted: existing employees require real contact, "
            "photo, and ID-proof data before they can be migrated safely."
        )

    for user in User.objects.using(using).all().iterator():
        if (
            user.role != "SUPERADMIN"
            or not user.is_superuser
            or user.restaurant_id is not None
            or user.public_id is not None
        ):
            raise RuntimeError("Super Admin migration aborted: invalid platform scope.")
        UserProfile.objects.using(using).create(
            user_id=user.pk,
            role=user.role,
            restaurant_id=user.restaurant_id,
            public_id=user.public_id,
        )


def restore_user_fields(apps, schema_editor):
    User = apps.get_model("dineva", "User")
    UserProfile = apps.get_model("dineva", "UserProfile")
    using = schema_editor.connection.alias
    for profile in UserProfile.objects.using(using).all().iterator():
        User.objects.using(using).filter(pk=profile.user_id).update(
            role=profile.role,
            restaurant_id=profile.restaurant_id,
            public_id=profile.public_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('dineva', '0005_user_username_authentication'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('OWNER', 'Owner'), ('KITCHEN_STAFF', 'Kitchen Staff'), ('WAITER', 'Waiter')], max_length=20)),
                ('public_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, storage=dineva.storage.get_private_storage, upload_to=dineva.storage.employee_photo_upload_to, validators=[dineva.validators.validate_profile_photo])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='dineva.restaurant'),
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='dineva_user_role_scope_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='users_public_id_matches_role',
        ),
        migrations.RunPython(copy_user_profiles, restore_user_fields),
        migrations.RemoveField(
            model_name='user',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.CreateModel(
            name='EmployeeIDProof',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='id_proof', serialize=False, to='dineva.userprofile')),
                ('proof_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('DRIVING_LICENSE', 'Driving License'), ('PASSPORT', 'Passport'), ('VOTER_ID', 'Voter ID'), ('OTHER_GOVERNMENT_ID', 'Other Government ID')], max_length=24)),
                ('file', models.FileField(storage=dineva.storage.get_private_storage, upload_to=dineva.storage.employee_id_proof_upload_to, validators=[dineva.validators.validate_id_proof_file])),
                ('mime_type', models.CharField(editable=False, max_length=50)),
                ('size_bytes', models.PositiveIntegerField(editable=False)),
                ('sha256', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee_id_proofs',
            },
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['restaurant', 'role'], name='profiles_rest_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('public_id__isnull', True), ('restaurant_id__isnull', True), ('role', 'SUPERADMIN')), models.Q(('address__isnull', False), ('contact__isnull', False), ('photo__isnull', False), ('public_id__isnull', False), ('restaurant_id__isnull', False), ('role__in', ['OWNER', 'KITCHEN_STAFF', 'WAITER'])), _connector='OR'), name='profiles_role_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('public_id__isnull', True), ('role', 'SUPERADMIN')), models.Q(('public_id__startswith', 'OWN-'), ('role', 'OWNER')), models.Q(('public_id__startswith', 'WTR-'), ('role', 'WAITER')), models.Q(('public_id__startswith', 'KST-'), ('role', 'KITCHEN_STAFF')), _connector='OR'), name='profiles_public_id_matches_role'),
        ),
    ]
